{
 "title": "Backup monitoring dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cores Used (from limits)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 \n* \nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m]))\n/\nsum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"})\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cores Used Top Pod (from limits)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1,\n  100\n  *\n  sum by (pod) (\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])\n  )\n  /\n  sum by (pod) (\n    kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"}\n  )\n)\n"
      }
     ]
    },
    {
     "title": "CPU Cores Usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Used (from limits)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits:memory:running{namespace=~\"$namespace\"})\n*\nsum(container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory  Used Top Pod (from limits)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1,\n  100\n  /\n  sum by (pod) (kube_pod_container_resource_limits:memory:running{namespace=~\"$namespace\"})\n  *\n  sum by (pod) (container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})\n)"
      }
     ]
    },
    {
     "title": "Memory Usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Storage Used (from capacity)",
     "type": "gauge",
     "description": "Persistent Storage",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})\n*\nsum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Storage Used Top PVC  (from capacity)",
     "type": "gauge",
     "description": "Persistent Storage",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1,\n  100\n  /\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})\n  *\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})\n)"
      }
     ]
    },
    {
     "title": "Persistent Storage Used by PVC",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Storage Throughput Read",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Storage Throughput Write",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\"}[5m]))\n"
      }
     ]
    },
    {
     "title": "Storage Troughput (read & write) by Pod",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_fs_reads_bytes_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "(read) {{pod}}"
      },
      {
       "expr": "sum by (pod) (container_fs_writes_bytes_total:sum_rate5m{namespace=~\"$namespace\"}) * -1",
       "legendFormat": "(write) {{pod}}"
      }
     ]
    },
    {
     "title": "Network Bandwidth Receive",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_network_receive_bytes_total:sum_rate5m{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Network Bandwidth Transmit",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_network_transmit_bytes_total:sum_rate5m{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Network Bandwidth (receive & transmit) by Pod",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "(receive) {{pod}}"
      },
      {
       "expr": "sum by (pod) (container_network_transmit_bytes_total:sum_rate5m{namespace=~\"$namespace\"}) * -1",
       "legendFormat": "(transmit) {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace CPU Cores Quota ($namespace)",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (namespace) (\n  kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"requests.cpu\"}\n)"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"requests.cpu\"})"
      },
      {
       "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"requests.cpu\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"requests.cpu\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"limits.cpu\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"limits.cpu\"})"
      },
      {
       "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"limits.cpu\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"limits.cpu\"})"
      }
     ]
    },
    {
     "title": "Namespace Memory Quota ($namespace)",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"requests.memory\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"requests.memory\"})"
      },
      {
       "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"requests.memory\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"requests.memory\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"limits.memory\"})"
      },
      {
       "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"limits.memory\"})"
      },
      {
       "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"limits.memory\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"limits.memory\"})"
      }
     ]
    },
    {
     "title": "Cores Requested",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Cores Limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Cores  Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Cores Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"})\n-\nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m]))\n"
      }
     ]
    },
    {
     "title": "Cores Wasted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})\n-\nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])) > 0\n"
      }
     ]
    },
    {
     "title": "Memory Requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace=~\"$namespace\"})\n-\nsum(container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Wasted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})\n-\nsum(container_memory_working_set_bytes:sum{namespace=~\"$namespace\"}) > 0"
      }
     ]
    },
    {
     "title": "Cores Used (from requests)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:cpu:running{namespace=~\"$namespace\"})\n*\nsum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Cores Used (from requests)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"$namespace\"})\r\n/\r\nsum(kube_pod_container_resource_requests:cpu:running{namespace=~\"$namespace\"})",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Cores Used, Requests, Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total:sum_rate5m{namespace=~\"$namespace\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:cpu:running{namespace=~\"$namespace\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:cpu:running{namespace=~\"$namespace\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Limits/Requests Ratio",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:cpu:running{namespace=~\"$namespace\"})\n*\nsum(kube_pod_container_resource_limits:cpu:running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Used (from requests)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})\n*\nsum(container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Used (from requests)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Memory Used, Requests, Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:memory:running{namespace=~\"$namespace\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Limits/Requests Ratio",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})\n*\nsum(kube_pod_container_resource_limits:memory:running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "CPU Cores by Container",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=~\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (\n  rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])\n)"
      },
      {
       "expr": "(\n  sum by (container, pod) (\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])\n  )\n)\n/\n(\n  sum by (container, pod) (\n    kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}\n  )\n)"
      },
      {
       "expr": "sum by (container, pod) (\n  avg(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])) \n  * on (pod, namespace) group_left() \n  kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\"}\n) "
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_limits:cpu:running{namespace=~\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (container_cpu_cfs_throttling:percent{namespace=~\"$namespace\"})"
      },
      {
       "expr": "(\n  sum by (container, pod) (\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])\n  )\n)\n/\n(\n  sum by (container, pod) (\n    kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"}\n  )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_limits:cpu:running{namespace=~\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_requests:cpu:running{namespace=~\"$namespace\"})"
      },
      {
       "expr": "(\r\n  sum by (container, pod) (\r\n    kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}\r\n  ) \r\n  - \r\n  sum by (container, pod) (\r\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])\r\n  )\r\n)\r\nand\r\n(\r\n  sum by (container, pod) (\r\n    kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}\r\n  ) * 0.75 \r\n  > \r\n  sum by (container, pod) (\r\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])\r\n  )\r\n)\r\nand\r\n(\r\n  sum by (container, pod) (\r\n    kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}\r\n  ) > 0.1\r\n)\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\r\n  sum by (container, pod) (\r\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])\r\n  )\r\n  -\r\n  sum by (container, pod) (\r\n    kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}\r\n  )\r\n)\r\nand\r\n(\r\n  sum by (container, pod) (\r\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])\r\n  )\r\n  >\r\n  sum by (container, pod) (\r\n    kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"} * 1.75\r\n  )\r\n)\r\nand\r\n(\r\n  sum by (container, pod) (\r\n    kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}\r\n  ) \r\n  > 0.1\r\n)\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory by Container",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})"
      },
      {
       "expr": "sum by (container,pod) (avg_over_time(container_memory_working_set_bytes:sum{namespace=~\"$namespace\"}[1d]) * on(pod,namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_limits:memory:running{namespace=~\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_limits:memory:running{namespace=~\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_limits:memory:running{namespace=~\"$namespace\"})\n/\nsum by (container, pod) (kube_pod_container_resource_requests{namespace=~\"$namespace\"})"
      },
      {
       "expr": "sum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})\r\n-\r\nsum by (container, pod) (container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"}) * 0.75 > sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"}) > 0.1"
      },
      {
       "expr": "sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})\r\n-\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"}) * 1.75 < sum by (container, pod) (container_memory_working_set_bytes:sum{namespace=~\"$namespace\"})\r\nand\r\nsum by (container, pod) (kube_pod_container_resource_requests:memory:running{namespace=~\"$namespace\"}) > 0.1"
      }
     ]
    },
    {
     "title": "CPU Cores Recommended by VPA",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by (container, target_kind, target_name) (kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=~\"$namespace\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Memory Recommended by VPA",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container, target_kind, target_name) (kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=~\"$namespace\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Persistent Storage",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})"
      },
      {
       "expr": "avg by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})"
      },
      {
       "expr": "avg by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})\n/\navg by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})"
      },
      {
       "expr": "avg by (persistentvolumeclaim) (avg_over_time(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}[1d]))"
      },
      {
       "expr": "avg by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Persistent Storage Used (from capacity)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})\n/\navg by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores Usage by Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Cores Usage by Container (from limits)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m]))\n/\nskube_pod_container_resource_limits:cpu:running{namespace=~\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "CPU CFS Throttling by Containers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "container_cpu_cfs_throttling:percent{namespace=~\"$namespace\"}",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage by Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage by Container (from limits)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"})\n/\nsum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Storage Troughput by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Write Storage Troughput by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Read Storage IOPS by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{container}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Write Storage IOPS by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Persistent Storage Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Persistent Storage Used (from capacity)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by(persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})\n/\navg by(persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Network Bandwidth by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Network Bandwidth by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Network Packets by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Network Packets Dropped by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets Dropped by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}